spring:
  datasource:
    driver-class-name:  com.mysql.jdbc.Driver
    url: jdbc:mysql://:3306/seckill?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: CCZK@130788

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
